use_frameworks!

platform :ios, '10.0'

target 'Telereso_Example' do
  pod 'Telereso', :path => '../'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'SDWebImage'

  target 'Telereso_Tests' do
    inherit! :search_paths
  end
end
